language: swift
osx_image: xcode9.3
script:
  - cd Example
  - xcodebuild -workspace S2GeometrySwift.xcworkspace -scheme S2GeometrySwift-Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: ./tools/cocoapods.sh
  on:
    tags: true
